### ISSUE TITLE
Upgrade version of vcdvcd

### ISSUE THREAD

**Issue by shareefj** [ics-jku/wal#12]
Hi,

you seem to be depending on a broken version of vcdvcd.py.  After pip installing `wal-lang`, I get the following error:

```
(.venv) shareefj@JALAPINO:~/git/wal$ wal
Traceback (most recent call last):
  File "/home/shareefj/git/wal/.venv/bin/wal", line 5, in <module>
    from wal.wal import run
  File "/home/shareefj/git/wal/.venv/lib/python3.10/site-packages/wal/wal.py", line 7, in <module>
    from wal.core import Wal
  File "/home/shareefj/git/wal/.venv/lib/python3.10/site-packages/wal/core.py", line 6, in <module>
    from wal.trace import TraceContainer
  File "/home/shareefj/git/wal/.venv/lib/python3.10/site-packages/wal/trace.py", line 5, in <module>
    from vcdvcd import VCDVCD, StreamParserCallbacks
  File "/home/shareefj/git/wal/.venv/lib/python3.10/site-packages/vcdvcd/__init__.py", line 1, in <module>
    from .vcdvcd import *
  File "/home/shareefj/git/wal/.venv/lib/python3.10/site-packages/vcdvcd/vcdvcd.py", line 355, in <module>
    class Scope(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

and it looks like at some point they've tried to fix this:  https://github.com/cirosantilli/vcdvcd/commit/9c9b7c1aaa7a6bcc4e254e3557cc00a9ec1c7bd0

**Comment by shareefj** [comment]
Installing vcdvcd to 2.3.3 seems to at least enable me to launch `wal`.

**Comment by LucasKl** [comment]
I replaced vcdvcd with pyDigitalWaveTools to resolve this error.
Now WAL should work with the latest Python version.
